nelmio_api_doc:
    documentation:
        info:
            title: BeerCoin
            description: Waluta studencka nabiera nowego znaczenia
            version: 1.0.0
        tags:
            - name: Beer
              description: Beer related endpoints
            - name: History
              description: History related endpoints
            - name: Offer
              description: Offer related endpoints
            - name: User
              description: User related endpoints
        components:
            schemas:
                Beer:
                    type: object
                    properties:
                        id:
                            type: string
                        brand:
                            type: string
                        name:
                            type: string
                        volume:
                            type: number
                        alcohol:
                            type: number
                        packing:
                            type: string
                History:
                    type: object
                    properties:
                        id:
                            type: string
                        offer:
                            $ref: '#/components/schemas/Offer'
                        counterparty:
                            $ref: '#/components/schemas/User'
                        amount:
                            type: number
                Offer:
                    type: object
                    properties:
                        id:
                            type: string
                        owner:
                            $ref: '#/components/schemas/User'
                        beer:
                            $ref: '#/components/schemas/Beer'
                        amount:
                            type: number
                        price:
                            type: number
                        total:
                            type: number
                        location:
                            $ref: '#/components/schemas/Location'
                        type:
                            type: string
                User:
                    type: object
                    properties:
                        id:
                            type: string
                        username:
                            type: string
                        name:
                            type: string
                        surname:
                            type: string
                        email:
                            type: string
                        phoneNumber:
                            type: string
                        balance:
                            type: number
                        location:
                            $ref: '#/components/schemas/Location'
                Location:
                    type: object
                    properties:
                        x:
                            type: number
                        y:
                            type: number
    areas:
        path_patterns:
            - ^/api/(?!(re|)doc(s|)(.json|)$) # Accepts routes under /api except /api/docs
