name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
      - name: Connect via SSH
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.PATH }}
            git restore composer.lock && git pull && composer install --no-dev --optimize-autoloader && bin/console doctrine:migration:migrate --no-interaction
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSHKEY }}